version: '3.6'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8880:80"
    depends_on:
      - app
    container_name: level_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
        -   db
    container_name: level_app

  db:
      image: mysql:8.3.0
      restart: always
      volumes:
          - ./tmp/db:/var/lib/mysql
      environment:
          MYSQL_DATABASE: laravel_project
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "8000:3306"
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      container_name: level_db

  phpmyadmin:
      depends_on:
          -   db
      image: phpmyadmin:latest
      container_name: level_phpmyadmin
      restart: always
      ports:
          -   "8080:80"
      environment:
           PMA_HOST: db
           MYSQL_ROOT_PASSWORD: root
